/**
 * @externs
 * @suppress {duplicate}
 */
// NOTE: generated by tsickle, do not edit.

/** @record @struct */
function NeverTyped() {}
 /** @type {string} */
NeverTyped.prototype.x;

/** @record @struct */
function OtherLib() {}
 /** @type {string} */
OtherLib.prototype.y;
